services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback-app
    env_file:
      - .env.local
    ports:
      - "4001:4001"
    volumes:
      - feedback_data:/app/data
    restart: always

volumes:
  feedback_data:
