services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedbacks-app
    env_file:
      - .env.local
    ports:
      - "4001:4001"
    volumes:
      - feedbacks_data:/app/data
    restart: always

volumes:
  feedbacks_data:
