services:
  structurizr:
    image: structurizr/structurizr
    container_name: feedback-structurizr
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/local/structurizr
    command: local
    restart: unless-stopped

    environment:
      - STRUCTURIZR_WORKSPACE=workspace.dsl